server:
  port: 8777

spring:
  application:
    name: client
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML5
  mvc:
    static-path-pattern: /**


eureka:
  client:
    service-url:
      defaultZone:  http://192.168.0.104:8761/eureka/